---
title: "Bildungsreformen"
output: html_document
---

```{r echo=FALSE, include=FALSE}
# Run the code necessary to get a list named res to access all the results. (Returned from listifyResults(.)) Probably it makes sense to load from disk, because caluclating every time is really slow.
res <- readRDS(file="results.RData")
format <- function(result, flipsign = FALSE) {
  if (flipsign) {
    result = - result
  }
  toString(round(result,2))
}
```

## Bafög Reform 1990

Im Jahr 1990 wurde die staatliche Förderung von Studierenden nach dem Bundesausbildungsförderungsgesetz (BAföG) grundlegend zu gunsten der BAföG berechtigten Studierenden angepasst. Zwischen 1983 und 1989 bestand die BAföG Leistung aus einem zinsfreien Darlehen, das nach Abschluss des Studiums vollständig zurückgezahlt werden musste. Nach der Reform im Jahr 1990 wurde im Regelfall etwa die Hälfte des Darlehens als Zuschuss gewährt, der nicht zurückgezahlt werden muss. Es sollten somit die Anreize ein Universitätsstudium aufzunehmen für Studierende deren Eltern über geringe Einkommen verfügen verbessert werden. [Baumgartner & Steiner (2006)](https://ideas.repec.org/p/iza/izadps/dp2034.html) evaluieren den Effekt der BAföG Reform auf die Anzahl an geförderten Studierenden die ein Studium an deutschen Universitäten aufnehmen. Es wird ein Effekt von 4 Prozentpunkten auf die Wahrscheinlichkeit ein Universitätsstudium aufzunehmen gefunden. Dieser Schätzer ist zentral für die Berechnung des MVPF.

Der Wert der Reform für die Begünstigten der Reform, also den von BAföG geförderten Studierenden, besteht aus zwei Effekte. Zunächst erhalten Studierende die BAföG beziehen `r format(res$bafoegRepayment$bafoeg_valuation)` Euro (Barwert diskontiert über die Dauer des Studiums) durch die Erlassung von 50% der BAföG-Schulden. Studierende die aufgrund der BAföG Reform ein Studium aufnehmen, also diejenigen die nicht studiert hätten, wenn die Reform nicht durchgeführt worden wäre, profitieren aufgrund der hohen Bildungsrenditen in Deutschland stark von der Reform. Der Effekt der zusätzlichen Bildung wird mithilfe einer Einkommensprojektion auf Basis von administrativen Daten des IAB abgeschätzt. Es ergibt sich eine Zunahme des erwarteten Einkommen pro BAföG-Berechtigten von `r format(res$bafoegRepayment$net_income_increase)` Euro. Die Summe der Zahlungsbereitschaften für die Reform beträgt somit `r format(res$bafoegRepayment$willingness_to_pay)` Euro.

Die Kosten des Staates setzen sich aus vier Komponenten zusammen. Zunächst muss der Staat auf 50% der Rückzahlung des Kredits verzichten. Es entstehen Kosten in Höhe von `r format(res$bafoegRepayment$bafoeg_valuation)` Euro pro BAföG-Berechtigten. Die zusätzlichen Studierenden verursachen zusätzliche Bildungsausgaben in Höhe von `r format(res$bafoegRepayment$education_cost)` Euro. Die Berechnung dieser Kosten beruht auf Daten des [statistischen Bundesamts](https://www.statistischebibliothek.de/mir/receive/DESerie_mods_00000117) über die jährlichen Ausgaben pro Studierenden an deutschen Universitäten. Ebenso steigt durch die zusätzlichen Studienanfänger die Anzahl an von BAföG geförderten Studenten. Diese Kostenkomponente wird auf `r format(res$bafoegRepayment$bafoeg_cost)` Euro geschätzt. Letztlich kann der Staat einen erheblichen Teil der zusätzlichen Ausgaben durch zusätzliche Steuereinnahmen zurückgewinnen. Studierende, die aufgrund der Reform ein höheres Bildungsniveau erreichen, erzielen über ihre gesamte berufliche Laufbahn höhere Bruttoeinkommen, wodurch zusätzliches Steueraufkommen generiert wird. Unter Verwendung der zuvor genannten Einkommensprojektion ergibt sich ein zusätzliches Steueraufkommen von `r format(res$bafoegRepayment$tax_revenue_increase, T)` Euro pro BAföG-Berechtigten. Die Summe der Effekte auf das Budget des Staates beträgt `r format(res$bafoegRepayment$government_net_costs)` Euro.

Der Marginal Value of Public Funds ist definiert als das Verhältnis der Wert der Reform für die Begünstigten der Reform zu den fiskalischen Kosten der Reform. Folglich ergibt sich ein MVPF von `r format(res$bafoegRepayment$mvpf)` für die BAföG Reform des Jahres 1990. Pro Euro Steuergeld der in die Finanzierung der BAföG Reform investiert wurden, erhielten BAföG berechtigte Studierende einen Wert von `r format(res$bafoegRepayment$mvpf)` Euro.

## Bafög Reform 2001
Eine Reform des BAföG (Bafög) aus dem Jahr 2001 erweiterte den Kreis der Bafög Berechtigten. Das elterliche Einkommen, bis zu welchem die gesamte Förderung beansprucht werden kann, wurde um circa 20% angehoben. Dies hatte zur Folge, dass die Anzahl an Bafög Berechtigen Studierenden um mehr als 50% zunahm. Baumgartner & Steiner (2006) untersuchen, inwiefern es dieser Politikmaßnahme gelang die Anzahl an Studienanfänger zu erhöhen. Mit einem Difference-in-Difference Ansatz finden die Autoren, dass die Studienanfängerquote um 1,5 Prozentpunkte gesteigert werden konnte. Zur Evaluierung dieser Reform im Rahmen des MVPF Frameworks, müssen sowohl der Wertschätzung (Zahlungsbereitschaft) der Bafög Bezieher für die Implementierung der Reform, als auch die Kosten die auf Seite des Staates entstehen berechnet werden. Die Zahlungsbereitschaft setzt sich aus zwei Komponenten zusammen. Erstens erhalten weitere Studierende nun BAföG Förderung, wovon nur circa die Hälfte zurückgezahlt werden muss. Dieser Effekt beträgt gemittelt über alle potenziellen Studienanfänger `r format(res$bafoeg2001$reform_valuation)` Euro. Dazu kommt das gestiegene erwartete Einkommen welches Studierende die aufgrund des erweiterten Bafög ein Studium aufnehmen erzielen. Zur Berechnung der Bildungsrenditen wird eine Einkommensprojektion auf Basis von Daten des IAB verwendet. Gemittelt über alle potenziellen Studienanfänger ergibt sich ein Effekt von `r format(res$bafoeg2001$net_income_increase)` Euro.

Demgegenüber stehen die fiskalischen Kosten. Hier werden drei Komponenten berücksichtigt. Die Auszahlung der BAföG-Föderung an weitere Studierende verursacht diskontiert unter Berücksichtigung der Rückzahlung von 50% der Förderung, Kosten in Höhe von `r format(res$bafoeg2001$program_cost)` Euro. Zur Berechnung dieses Wertes wurde die durchschnittliche Höhe der BAföG-Förderung im Jahr 2001 verwendet und eine durchschnittliche Studiendauer von 5 Jahren angenommen. Die zusätzlichen Studienanfänger verursachen Kosten im Bildungssystem. Da deutsche Universitäten staatlich finanziert sind, kommt der Staat für die Mehrkosten des Studiums gegenüber einer Ausbilung auf. Aus Daten des statistischen Bundesamt über die Ausgaben für Universitäten und Berufsschulen errechnen sich Mehrkosten in Höhe von `r format(res$bafoeg2001$education_cost)`. Schließlich profitiert der Staatshaushalt von gestiegenen Einkommen der zusätzlichen Studienanfänger und den damit einhergehenden Einkommenssteuerzahlungen. Unter Berücksichtigung des deutschen Einkommenssteuersystems ergibt sich gemäß der verwendeten Einkommensprojektion ein diskontiertes zusätzliches Steueraufkommen in Höhe von `r format(res$bafoeg2001$tax_revenue_increase, T)` Euro. Nach aufsummieren der fiskalischen Kosten und der Zahlungsbereitschaft für die Reform ergibt sich ein Kosten-Nutzen Verhältnis von `r format(res$bafoeg2001$mvpf)`.

## Realschulabschluss mit Beendigung 10. Klasse Gymnasium
Zwischen 1965 und 1996 wurde in allen deutschen Bundesländern die mittlere Reife, also der Realschulabschluss als Zwischenabschluss des Gymnasiums eingeführt. Mit erfolgreicher Beendigung der 10. Klasse erhalten Schüler die mittlere Reife, auch wenn sie die Oberstufe des Gymnasiums nicht abschließen. Diese Reform sollte verhindern, dass Schüler bei nicht Bestehen des Abiturs die Schule ohne Abschluss verlassen müssen. Die Reform ist insbesondere für Schüler relevant, die die Möglichkeit haben ein Gymnasium zu besuchen, aber aufgrund der Möglichkeit des späten Scheiterns in der Oberstufe sich dazu entscheiden die Realschule zu besuchen. Der Realschulabschluss nach der 10. Klasse stellt eine Versicherung gegen diesen Fall dar und könnte somit zusätzlichen Schülern den Anreiz geben das Gymnasium zu besuchen.

[Obergruber & Zierow (2020)](https://ideas.repec.org/a/eee/ecoedu/v75y2020ics0272775718307179.html) zeigen, dass die Reform den gewünschten Effekt hatte. Die Wahrscheinlichkeit das Gymnasium erfolgreich abzuschließen stieg um 24.5 Prozentpunkte. Im Schnitt verlängerte die Reform die durchschnittliche Anzahl der Schuljahre um 0.767. Da diese Reform keine direkten Kosten versucht sind lediglich die vom Staat getragenen Kosten für die zusätzlichen Schuljahre am Gymnasium relevant. Aus Daten des [statistischen Bundesamts](https://www.statistischebibliothek.de/mir/receive/DESerie_mods_00002310) über die finanziellen Aufwendungen pro Schüler gestaffelt nach Schulart errechnen sich zusätzliche Kosten in Höhe von `r format(res$interimDegrees$education_cost, T)`. Diese Kosten sind kleiner als der erwartete Anstieg der Steuereinnahmen aufgrund des höheren Bildungsniveaus (`r format(res$interimDegrees$tax_revenue_increase)`€). Zur Berechnung der Bildungsrenditen über das gesamte Berufsleben werden administrative Daten des IAB verwendet. Die Bildungsreform hatte folglich netto einen positiven Effekt auf das Staatsbudget. Ebenso profitieren Schüler von dem Abschluss des Gymnasiums. Es wird eine Zunahme des Lebenszeitnettoeinkommen von `r format(res$interimDegrees$net_income_increase)` prognostiziert. Das Kosten-Nutzen Verhältnis, definiert als Marginal Value of Public Funds, ist somit unendlich. Es entstanden dem Staat keine Kosten; es konnte sogar zusätzliches Steueraufkommen generiert werden während einige Schüler ebenso gestellt wurden durch ihr höheres Bildungsniveau.
