---
title: "Weiterbildung- und Trainingsprogramme"
output:
    html_document:
        fig_retina: 1
---

```{r echo=FALSE, include=FALSE}
# Run the code necessary to get a list named res to access all the results. (Returned from listifyResults(.)) Probably it makes sense to load from disk, because caluclating every time is really slow.
res <- readRDS(file="results.RData")

library(ggplot2)
library(rjson)
library(scales)
library(showtext)

number_of_js_plots <- 0

format <- function(result, flipsign = FALSE) {
  if (flipsign) {
    result = - result
  }
  prettyNum(round(result,2), big.mark = ".", decimal.mark = ",")
}


# Try to load the alternative font that is used in the pdf exports.
# If this font is not installed / cannot be found, the standard one will be used
tryCatch({
  plot_font <<- "Calibri"
  font_add(plot_font, "OpenSans-Regular.ttf")
}, error = function(e) {
  warning("Font is not installed. Plots are going to use the standard font instead.")
  plot_font <<- "sans"
})
showtext_auto()

makePlot <- function(program, type, heading = "", js = T) {
  if (missing(program) || missing(type)) {
    print("Need to specify program and type")
    return(0)
  }

  label <- switch(type, "wtp" = "Zahlungsbereitschaft", "cost" = "Fiskalische Kosten")
  variable <- switch(type, "wtp" = "willingness_to_pay", "cost" = "government_net_costs")

  if (js == TRUE) {
    if (number_of_js_plots > 0) {
      return(htmltools::HTML(sprintf(r"(<canvas id="chart%s" style="width: 100%%; height: %ipx"></canvas>
      <script>
      async function drawGraphs() {
        while(true) {
          if (content_loaded) {
            break;
          }
          else {
            await new Promise(r => setTimeout(r, 200));
          }
        }
        drawChart(unmodified_dataset, "%s", "%s", "%s");
      }
      drawGraphs();
      </script>
      )", paste0(program,variable), 170, variable, program, heading)))
    }

    # We have to split this in multiple strings because sprintf cannot print into strings longer than 8000 characters..
    variable_decs <- sprintf(r"(<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.0/chart.min.js"></script>
  <canvas id="chart%s" style="width: 100%%; height: %ipx"></canvas>
  <script>
    var unmodified_dataset;
    var document_root = "";
    var content_loaded = false;
    var additional_program_info;
    var categories;
    var colors;
    var variable_mapping;
    var tooltip_counter = 1;
    )", paste0(program,variable), 170)

    functions <- r"(async function loadJSON(url) {
    var json;
    await fetch(url).then(response => {
        json = response.json();
    });
    return json;
    }

    async function readjson(assumption_string) {
    // depends on additional_program_info being loaded as we need some way of determining which government policies exist before this function can be called

    // This will be the array carrying the data. It should be compatible to the array returned from readcsv with the only difference that the json format omits all the keys with NA values.
    var json_as_array;

    // First we need to get a list of all programs. Where the entries are strings
    var programs = additional_program_info.map(program => {
        return program.program_identifier;
    });

    // Individual json requests to all of the programs
    var requests = programs.map(program => {
        // Note: usually one would expect that this code runs the loadJSON and stores the
        // result in requests. This is not what we want, as the http requests should be
        // run in parallel for better performance. Fortunately, this is not what is happening. loadJSON is a async function. And async functions return promises. which are not automatically resolved.
        return loadJSON(document_root + "data/" + program + "/" + assumption_string + ".json");
    });

    // Resolve promises in parallel
    await Promise.all(requests).then((result) => json_as_array = result);

    // This loop merges the loaded ddata with the details about each reform (description, sources, age etc..) form programs.json. The resulting array of objects then contains all relevant data.

    for (var i = 0; i < json_as_array.length; i++) {
        Object.assign(json_as_array[i], additional_program_info[i]);
        // Rename program identifier to program. (For compatibility with the old solution)
        json_as_array[i]["program"] = json_as_array[i]["program_identifier"];
        delete json_as_array[i]["program_identifier"];
    }

    unmodified_dataset = JSON.parse(JSON.stringify(json_as_array));

    // sort by category & ensure that categories is defined already
    if (typeof(categories) != "undefined") {
        unmodified_dataset.sort(function(a, b){
            return categories.indexOf(a.category) - categories.indexOf(b.category);
        });
    }
    return json_as_array;
}

function getScalesMinMax(program) {
    // we want the same scale on all of the bar plots. To ensure this we calculate the required min length of the x-axis for each plot and apply the largest to all.
    let relevant_datapoint = unmodified_dataset.find(function (datapoint) {
        return (datapoint.program === program);
    });

    let max = addAllPositivesSubtractAllNegatives([
        Math.abs(parseFloat(relevant_datapoint["willingness_to_pay"]),
            -Math.abs(parseFloat(relevant_datapoint["government_net_costs"])))
    ]);
    let mappingEntry;

    for (let i = 0; i < variable_mapping.length; i++) {
        if (variable_mapping[i].program === program) {
            mappingEntry = variable_mapping[i];
            break;
        }
    }

    barComponents = mappingEntry["willingness_to_pay"];
    let array = [];
    let component;
    for (component in barComponents) {
        array.push(parseFloat(relevant_datapoint[component]));
    }
    max = Math.max(addAllPositivesSubtractAllNegatives(array), max);


    barComponents = mappingEntry["government_net_costs"];
    array = [];
    for (component in barComponents) {
        array.push(parseFloat(relevant_datapoint[component]));
    }
    max = Math.max(addAllPositivesSubtractAllNegatives(array), max);

    return (max);
}

function selectColor(number, background = false) {
    // returns a string in the format rgba(123,123,123,0.6)
    let background_opa = 0.7
    let foreground_opa = 0.9
    if (number > colors.length) {
        console.log("Color not in range of supplied colors in colors.json");
        // Reuse last color in this case
        number = colors.length;
    }
    color_triple = colors[number - 1];
    return `rgba(${color_triple[0]},${color_triple[1]},${color_triple[2]},${background ? background_opa : foreground_opa})`;
}

function addAllPositivesSubtractAllNegatives(array) {
    let negative = 0;
    let positive = 0;
    let i;
    for (i = 0; i < array.length; i++) {
        if (array[i] > 0) {
            positive += array[i];
        }
        else {
            negative -= array[i];
        }
    }
    return (Math.max(Math.abs(positive), Math.abs(negative)));
}

function generateBarData(csv_as_array, variable_to_plot, program) {
    let datasets = [];
    let barComponents;
    let bar_counter = 1;
    let relevant_datapoint = unmodified_dataset.find(function (datapoint) {
        return (datapoint.program === program);
    });
    if (variable_to_plot === "mvpf") {
        datasets.push({
            label: "Government Net Cost",
            data: [parseFloat(relevant_datapoint["government_net_costs"])],
            backgroundColor: selectColor(bar_counter, true),
            borderColor: selectColor(bar_counter),
        });
        datasets.push({
            label: "Willingness to Pay",
            data: [relevant_datapoint["willingness_to_pay"]],
            backgroundColor: selectColor(bar_counter + 1, true),
            borderColor: selectColor(bar_counter + 1),
        });
        bar_counter += 2;
        return (datasets);
    }
    for (let i = 0; i < variable_mapping.length; i++) {
        if (variable_mapping[i].program === program) {
            barComponents = variable_mapping[i][variable_to_plot];
            break;
        }
    }
    for (component in barComponents) {
        datasets.push({
            label: barComponents[component],
            data: [relevant_datapoint[component]],
            backgroundColor: selectColor(bar_counter, true),
            borderColor: selectColor(bar_counter)
        });
        bar_counter++;
    }
    bar_counter = 1;
    return (datasets);
}
)"
    drawChart <- r"(function drawChart(csv_as_array, variable_to_plot, program, heading = "") {
    let chartElement = document.getElementById('chart' + program + variable_to_plot);
    // Get Plotting range
    let range = getScalesMinMax(program);
    let chart = new Chart(chartElement, {
        type: 'bar',
        data: {
            labels: '.', // In ChartJS Beta 3.0 this could be left empty. If we leave it empty in 3.3, there is no graph drawn anymore. (And the tooltip is now shared for all areas of the chart in 3.3).
            datasets: generateBarData(csv_as_array, variable_to_plot, program)
        },
        options: {
            indexAxis: 'y',
            responsive: false,
            maintainAspectRatio: false,
            aspectRatio: 4,
            //devicePixelRatio: 4, //Set this to save a high res png. Otherwise leave default
            plugins: {
                title: {
                    display: true,
                    text: heading,
                    align: "start",
                    position: "top"
                },
                legend: {
                    position: 'bottom',
                    usePointStyle: true,
                    onClick: () => {} //This disables the ability to click on the legend and remove effects.
                },
                tooltip: {
                    enabled: true,
                    displayColors: false,
                    bodyColor: "black",
                    backgroundColor: "white",
                    borderWidth: 2,
                    cornerRadius: 8,
                    bodyFont: {weight: 600},
                    borderColor: "#2b6ebe",
                    mode: 'nearest',
                    callbacks: {
                        title: function (data) {
                            return null;
                        }
                    }
                }
            },
            scales: {
                x: {
                    stacked: true,
                    ticks: {
                        maxTicksLimit: 3
                    },
                    grid: {
                        drawOnChartArea: false,
                        lineWidth: 0,
                        tickWidth: 1
                    },
                    min: -range,
                    max: range,
                    afterTickToLabelConversion: function(data) {
                        // this adds € signs to the tick marks on the x-axis.
                        let ticks = data.ticks;
                        for (var i = 0; i < ticks.length; i++) {
                            ticks[i].label = ticks[i].label.replace(".", "placeholder").replace(",", ".").replace("placeholder", ",") + "€";
                        }
                        return data;
                    }
                },
                y: {
                    stacked: true,
                    display: false
                }
            }
        }
    });
})"
    js_exec <- sprintf(r"(if (true) {
        // load the dataset:
        Promise.all([
        loadJSON(document_root + "data/programs.json"),
        loadJSON(document_root + "data/categories.json")
    ]).then(return_values => {
        additional_program_info = return_values[0];
        categories = return_values[1];
        return Promise.all([
            readjson("default"),
            loadJSON(document_root + "data/variable_mapping.json"),
            loadJSON(document_root + "data/colors.json")
        ]);
    }).then((return_values) => {
        variable_mapping = return_values[1];
        colors = return_values[2];
        drawChart(return_values[0], "%s", "%s", "%s");
        content_loaded = true;
    });
}
</script>)",variable, program, heading)
    number_of_js_plots <<- number_of_js_plots + 1
    return(htmltools::HTML(paste0(variable_decs, functions, drawChart, js_exec)))
  }


  variable_mapping = rjson::fromJSON(file = "variable_mapping.json")

  # Construct the dataset
  for (i in 1:length(variable_mapping)) {
    if (variable_mapping[[i]]$program == program) {
      relevant_data <- variable_mapping[[i]]
    }
  }

  colors <- c(rgb(46,139,87, maxColorValue = 255),
              rgb(30,144,255, maxColorValue = 255),
              rgb(255,165,0, maxColorValue = 255),
              rgb(220,20,60, maxColorValue = 255),
              rgb(0,128,128, maxColorValue = 255),
              rgb(0,0,139, maxColorValue = 255),
              rgb(255,20,147, maxColorValue = 255),
              rgb(165,42,42, maxColorValue = 255),
              rgb(154,205,50, maxColorValue = 255),
              rgb(196, 196, 126, maxColorValue = 255),
              rgb(189,189,189, maxColorValue = 255))

  getValue <- function(name) {
    return(res[[program]][[name]])
  }
  getRange <- function(data) {
    positives = 0
    negatives = 0
    for (i in 1:length(data$values)) {
      if (data$values[[i]] >= 0) {
        positives = positives + data$values[[i]]
      }
      else {
        negatives = negatives - data$values[[i]]
      }
    }
    return(max(c(positives, negatives)))
  }

  data <- data.frame(values = sapply(names(relevant_data[[variable]]), getValue),
                     labels = unlist(relevant_data[[variable]], use.names=FALSE), x = 0)

  plot <- ggplot(data) + geom_col(aes(y = values, x = x, fill = labels)) +
    coord_flip() + theme(legend.position = "bottom") +
    scale_y_continuous(labels = function(x) paste0(x, "€"), limits = c(-getRange(data), getRange(data))) +
    scale_fill_manual(values = colors) +
    scale_shape_manual(values = 21) +
    ylab(label) +
    guides(fill=guide_legend(ncol=3,byrow=TRUE)) +
    theme_minimal(base_size=20,  base_family=plot_font) %+replace%
      theme (
      # axis.line.x|y control whether the x and y axis are drawn. It can look stylish to omit one or both:
      # axis.line.y = element_blank() to omit
      # e.g: axis.line.x = element_line(color = "darkgrey", size = 0.5) to draw
      axis.line.y = element_blank(),
      axis.line.x = element_line(color = "darkgrey", size = 0.75),
      axis.title.y=element_blank(),
      panel.border = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_blank(),
      # Enable or Disable Axis ticks:
      axis.ticks = element_line(color = "darkgrey", size = 0.75),
      axis.ticks.y = element_blank(),
      # Removes Legend Explanation:
      legend.title=element_blank(),
      # Set location of legend:
      legend.position = "bottom",
      # Legend font size
      legend.text = element_text(size=10.5),
      # Axis (ticks) size
      axis.text = element_text(size=11.5),
      axis.text.y = element_blank(),
      # Axis label size
      axis.title = element_text(size=14),
      # Change Legend Stacking to vertical:
      legend.box="vertical"
      )
  print(plot)
}

```
## Der MVPF von Weiterbildung- und Trainingsprogrammen
In Deutschland gibt es eine Vielzahl von Weiterbildungs- und Trainingsprogrammen die aus öffentlichen Mitteln finanziert werden, um die Beschäftigungsaussichten von Arbeitssuchenden zu verbessern. Die Evaluierung von diesen Programmen ist Gegenstand ökonomischer Forschung. Grundsätzlich ist die verfügbare Literatur für Deutschland umfangreich. Die meisten Evaluierungsstudien zu arbeitsmarktpolitischen Maßnahmen konzentrieren sich auf die Effektivität hinsichtlich der Reduktion von Arbeitslosigkeit. Eine niedrigere Arbeitslosenquote senkt zwar fiskalischen Kosten durch die Verringerung der Zahl der Empfänger von Arbeitslosengeld. Der Effekt auf die Arbeitslosenquote ist aber nicht ausreichend um die genauen Auswirkungen auf den Staatshaushalt zu quantifizieren. Personen, die aufgrund einer Weiterbildungsmaßnahme eine Beschäftigung finden, können je nach ihrem Bruttoverdienst weiterhin Transferleistungen erhalten, aber auch Einkommenssteuer in relevanter Höhe zahlen. Zur Berechnung des MVPFs ist es daher essenziell, den Effekt eines Trainingsprogramms auf die zukünftigen Einkommen zu bestimmen. Da die Bildung von Humankapital während Ausbildungs- und Weiterbildungsprogrammen sich langfristig auswirken kann, sollten Einkommensdaten nach Möglichkeit über einen langen Zeitraum vorliegen. Ebenso müssen Information über die Kosten eines Trainingsprogramms, vorliegen. Infolgedessen ist der Kreis der Studien, für die ein plausibler MVPF berechnet werden kann, eingeschränkt.

Sind die relevanten Informationen verfügbar, ist die Berechnung des MVPFs relativ unkompliziert. Die Zahlungsbereitschaft entspricht der Änderung des Nettoeinkommens über den Beobachtungszeitraum der Studie. Es wird keine Extrapolation von Einkommensänderungen über den von der Studie untersuchten Zeitraum hinaus vorgenommen. In der Regel geben die der MVPF Rechnung zugrunde liegenden Studien jährliche Effekte auf das Bruttoeinkommen oder den kumulierten Effekt über den Beobachtungszeitraum der Studie an. Zahlungen, die ab dem Zeitpunkt der Ausgaben für das Trainingsprogramm in der Zukunft liegen, werden mit einer Diskontrate von 3 Prozent abgezinst. Mithilfe einer Simulation des deutschen Steuer- und Transfersystems wird berechnet welcher Teil der Bruttoeinkommensänderung auf den Staat und die Einkommensbezieher entfällt. In der Simulation wird das durchschnittliche Einkommen von in der jeweiligen Studie eingeschlossenen Personen verwendet, um die effektiven Grenzsteuersätze zu berechnen. Dabei wird bei niedrigen Einkommen der Erhalt bzw. der Entzug von Transfers im Rahmen des Arbeitslosengeld II berücksichtigt. Die für den MVPF relevanten Nettokosten eines Trainingsprogramms setzen sich lediglich aus zwei Komponenten zusammen: (i) den Vorabkosten für die Bereitstellung des Trainingsprogramms und (ii) dem Effekt auf das Steueraufkommen (inklusive des Effekts auf Transferzahlungen).

## Trainingsmaßnahmen
Biewen et al. (2014) untersuchen die Effektivität von Trainingsmaßnahmen. Unter Trainingsmaßnahmen fallen eine Reihe von Trainingsprogrammen mit einer kurzen Laufzeit von zwei bis zwölf Wochen (Im Durchschnitt etwas mehr als 4 Wochen). Die Trainingsmaßnahmen sollen helfen Chancen auf dem Arbeitsmarkt zu aufzuzeigen. Außerdem können spezifischen Fähigkeiten vermittelt werden und die Eignung für bestimmte Jobs überprüft werden. Biewen et al. (2014) greifen auf administrative Daten zurück, die Informationen über Teilnehmende an Trainingsprogrammen in den Jahren 2000-2002 enthalten. Der Datensatz enthält nur Beobachtungen aus Westdeutschland. Die Autoren schätzen den Effekt der Trainingsmaßnahmen auf die erzielten Einkommen im nächsten und übernächsten Jahr. Dabei wird der Effekt jeweils für Männer und Frauen, sowie für drei verschiedene Schichten, die nach Dauer der bereits vergangenen Arbeitslosigkeit gruppiert sind, separat angegeben. Der gemäß der Beobachtungszahl gewichtete Durchschnitt beträgt im ersten Jahr 239,22€ und im zweiten Jahr 1016,16€. Nach Berechnung der effektiven Besteuerung ergeben sich unter Berücksichtigung der Diskontrate von 3% für den MVPF relevante Effekte auf (i) das Nettoeinkommen von plus `r format(res$trainingMeasures$net_income_increase)`€ und (ii) auf das Steueraufkommen von plus `r format(res$trainingMeasures$tax_revenue_increase, T)`€. Biewen et al. (2014) geben die Ausgaben für die Finanzierung der Trainingsmaßnahmen mit 580€ pro Teilnehmer pro Monat an. Bei einer durchschnittlichen Trainingsdauer von 1,2 Monaten ergeben sich Kosten von 696€. Die Nettokosten betragen somit 696€ - `r format(res$trainingMeasures$tax_revenue_increase, T)`€ = `r format(res$trainingMeasures$government_net_costs)`€. Es wird ein Wert von `r format(res$retraining$willingness_to_pay)`€ / `r format(res$retraining$government_net_costs)`€ = `r format(res$retraining$mvpf)`€ pro investiertem Euro Steuergeld generiert.

## Berufliche Weiterbildung
Berufliche Weiterbildungen umfassen Aktivitäten zum Ausbau von beruflichen Kompetenzen. Die genauen Inhalte dieses Weiterbildungsprogramms sind nicht festgelegt. Sowohl Präsenzunterricht, Schulungen am Arbeitsplatz oder die Arbeit an einer Übungsfirma können Teil einer geförderten beruflichen Weiterbildung für Arbeitssuchende sein. Biewen et al. (2014) evaluieren die Effektivität von beruflichen Weiterbildungsmaßnahmen. Die Autoren greifen auf administrative Daten zurück, die Informationen über Teilnehmende an berufliche Weiterbildungen in den Jahren 2000-2002 enthalten. Der Datensatz enthält nur Beobachtungen aus Westdeutschland. Die Autoren schätzen den Effekt der beruflichen Weiterbildung auf die erzielten Einkommen in den zwei darauffolgenden Jahren. Dabei wird der Effekt jeweils für Männer und Frauen, sowie für drei verschiedene Schichten, die nach Dauer der bereits vergangenen Arbeitslosigkeit gruppiert sind, separat angegeben. Der gemäß der Beobachtungszahl gewichtete Durchschnitt beträgt im ersten Jahr -2902,55€ und im zweiten Jahr 1.274,99€. Nach Berechnung der effektiven Besteuerung ergeben sich unter Berücksichtigung der Diskontrate von 3% für den MVPF relevante Effekte auf (i) das Nettoeinkommen von minus `r format(res$classRoomTraining$net_income_increase, T)`€ und (ii) auf das Steueraufkommen von minus `r format(res$classRoomTraining$tax_revenue_increase, T)`€. Biewen et al. (2014) geben die Ausgaben für die Finanzierung der Trainingsmaßnahmen mit 664€ pro Teilnehmer pro Monat an. Bei einer durchschnittlichen Trainingsdauer von 7,5 Monaten ergeben sich Kosten von 4980€. Die Nettokosten betragen folglich 4.980€ + `r format(res$classRoomTraining$tax_revenue_increase, T)`€ = `r format(res$classRoomTraining$government_net_costs)`€. Es folgt ein MVPF von `r format(res$retraining$willingness_to_pay)`€ / `r format(res$retraining$government_net_costs)`€ = `r format(res$retraining$mvpf)`€. Der negative MVPF suggeriert, dass Arbeitssuchende von der Weiterbildung nicht profitieren können. Bei der Interpretation des MVPFs muss berücksichtigt werden, dass der negative Effekt auf das Einkommen ausschließlich auf das geringere Einkommen im Jahr der Weiterbildung zurückzuführen ist. Es liegt ein sogenannter Lock-in-Effekt vor. Durch die Weiterbildung wird die Aufnahme einer neuen Beschäftigung verzögert. Der positive Effekt auf das Einkommen im zweiten Jahr ist nicht ausreichend um den Lock-in-Effect zu kompensieren. Dennoch ist es plausibel, dass die berufliche Weiterbildung sich auch in den darauffolgenden Jahren positiv auswirkt. In diesem Fall könnte der MVPF mitunter deutlich unterschätzt werden. Ohne weitere Daten ist jedoch nicht möglich eine genauere Aussage zu treffen.

## Bildungsgutscheine
Im Jahr 2003 wurde ein Gutscheinsystem für die Vergabe von öffentlich finanzierten Trainings- und Fortbildungsprogrammen eingeführt. Sachbearbeiter vergaben einen Ausbildungsgutschein an Arbeitssuchende, wenn durch den Abschluss der Aus- oder Fortbildung mindestens eine Wahrscheinlichkeit von 70% besteht, dass wieder eine Arbeitsstelle gefunden wird. Es wird zwischen Schulungskursen die sich im Durchschnitt über 5 Monate erstrecken und vollwertigen Ausbildungslehrgängen mit einer Dauer von zweieinhalb Jahren unterschieden. Sachbearbeiter der Arbeitsagentur entscheiden über die Art der Fortbildung und über die genaue Fachrichtung. Arbeitssuchende können lediglich Präferenzen äußern. Die Bildungsgutscheine können dann bei einem regionalen Anbieter eingelöst werden. Die Auswahl des Anbieters obliegt den Arbeitssuchenden. Hierdurch sollte zusätzlicher Wettbewerb zwischen den privaten Anbietern von Fortbildungsleistungen geschaffen werden. Die Bildungsgutscheine müssen nicht eingelöst werden. Sobald jedoch das Fortbildungsprogramm begonnen wird, muss dieses in der Regel abgeschlossen werden. Zur Berechnung des MVPFs der Bildungsgutscheine werden Ergebnisse von Doerr et al. (2017) und Huber et al. (2016) kombiniert.  Doerr et al. (2017) geben den Effekt des Erhalts der Bildungsgutscheine auf das Einkommen für vier Jahre nach Erhalt des Bildungsgutscheins an. Die Arbeitssuchenden können nicht von dem Erhalt des Bildungsgutscheins profitieren. Im Durchschnitt verringert sich das jährliche Einkommen um 2.642,40€ im ersten Jahr, 2.970,60€ im zweiten Jahr, 2.039,04€ im dritten Jahr und 701,76€ im vierten Jahr. Die Autoren unterscheiden nicht zwischen den kürzen Schulungskursen und den Ausbildungslehrgängen. Um die Auswirkung der Einkommensänderungen auf das Nettoeinkommen und das Steueraufkommen zu berechnen, wird die effektive Steuerlast auf Basis von Einkommensinformationen von Huber et al. (2016) berechnet. Es ergeben sich für den MVPF relevante Effekte auf (i) das Nettoeinkommen von minus `r format(res$trainingVoucher$net_income_increase)`€ und (ii) auf das Steueraufkommen von minus `r format(res$trainingVoucher$tax_revenue_increase,)`€. Weder Doerr et al. (2017) noch Huber et al. (2016) enthalten Informationen über die Kosten die durch die Vergabe eines Bildungsgutscheins entstehen. Aus deskriptiven Statistiken von Doerr et al. (2016) ist bekannt, dass 78 Prozent der Bildungsgutscheine eingelöst werden. Der Anteil der Schulungsprogramme beträgt 71,1 Prozent. Um dennoch die Kosten der Bildungsgutscheine abschätzen zu können, wird angenommen, dass die monatlichen Kosten für Schulungsprogramme und Ausbildungslehrgänge den von Biewen et al. (2014) untersuchten beruflichen Weiterbildungen vor der Einführung des Gutscheinsystems entsprechen (631€). Unter Berücksichtigung der Dauer von Schulungsprogrammen und Ausbildungslehrgängen und einer Diskontrate von 3% ergeben sich durchschnittliche Kosten eines Bildungsgutscheins von `r format(res$trainingVoucher$program_cost)`€. Die Nettokosten betragen folglich `r format(res$trainingVoucher$program_cost)`€ + `r format(res$trainingVoucher$tax_revenue_increase)`€ = `r format(res$trainingVoucher$government_net_costs)`€. Der MVPF ist negativ. Das erwartete Einkommen von Arbeitssuchenden wird durch die Zuteilung eines Bildungsgutscheins in den ersten vier Jahren negativ beeinflusst. In der langen Frist können positive Effekte der Bildungsgutscheine nicht ausgeschlossen werden.


## Kurze Trainingsprogramme
 Unter kurzen Trainingsprogrammen werden verschiedene Trainingsprogramme deren Dauer weniger als 6 Monate beträgt zusammengefasst. Die meisten Trainingsprogramme finden in Vollzeit statt. Es wird das Ziel verfolgt, berufliche Kenntnisse und andere Fähigkeiten zu erweitern, um Beschäftigungsaussichten zu verbessern. Lechner et. al (2011) evaluieren die langfristigen Auswirkungen. Der Studie zugrunde liegen administrative Daten, die das Einkommen von Teilnehmer an verschieden Trainingsprogrammen in den Jahren 1992 bis 1994 über die nachfolgenden 8 Jahre umfassen. Der Datensatz ist auf Westdeutschland beschränkt. Die Autoren geben einen kumulierten Effekt der kurzen Trainingsprogramme auf das Einkommen von 41.832,6€ über 8 Jahre an. Nach Berechnung der effektiven Besteuerung ergeben sich unter Berücksichtigung der Diskontrate von 3% für den MVPF relevante Effekte auf (i) das Nettoeinkommen von plus `r format(res$shortTraining$net_income_increase)`€ und (ii) auf das Steueraufkommen von plus `r format(res$shortTraining$tax_revenue_increase, T)`€. Lechner et. al (2011) geben die Ausgaben für kurze Trainingsprogramme mit 4.439€ pro Teilnehmer an. Die Nettokosten betragen somit 4.439€ - `r format(res$shortTraining$tax_revenue_increase, T)`€ = `r format(res$shortTraining$government_net_costs)`€. Negative Nettokosten bei einer positiven Zahlungsbereitschaft sind gleichbedeutend mit einem unendlichen MVPF.

## Lange Trainingsprogramme
Lechner et. al (2011) evaluieren die langfristigen Auswirkungen von langen Trainingsprogrammen. Es werden verschiedene Trainingsprogramme deren Dauer mindestens 12 Monate beträgt zusammengefasst. Die meisten Trainingsprogramme finden in Vollzeit statt. Es wird das Ziel verfolgt, beruflichen Kenntnisse und andere Fähigkeiten zu erweitern, um Beschäftigungsaussichten zu verbessern. Der Studie zugrunde liegen administrative Daten, die das Einkommen von Teilnehmer an verschieden Trainingsprogrammen in den Jahren 1992 bis 1994 über die nachfolgenden 8 Jahre umfassen. Der Datensatz ist auf Westdeutschland beschränkt. Die Autoren geben einen kumulierten Effekt der kurzen Trainingsprogramme auf das Einkommen von 26.618,60€ über 8 Jahre an. Nach Berechnung der effektiven Besteuerung ergeben sich unter Berücksichtigung der Diskontrate von 3% für den MVPF relevante Effekte auf (i) das Nettoeinkommen von plus `r format(res$longTraining$net_income_increase)`€ und (ii) auf das Steueraufkommen von plus `r format(res$longTraining$tax_revenue_increase, T)`€. Lechner et. al (2011) geben die Ausgaben für lange Trainingsprogramme mit 9.930€ pro Teilnehmer an. Die Nettokosten betragen somit 9.930€ - `r format(res$longTraining$tax_revenue_increase, T)`€ = `r format(res$longTraining$government_net_costs)`€. Der MVPF beträgt `r format(res$longTraining$willingness_to_pay)`€ / `r format(res$longTraining$government_net_costs)`€ = `r format(res$longTraining$mvpf)`.

## Berufliche Neuausrichtung
Unter Beruflicher Neuausrichtung werden Trainingsprogramme zusammengefasst, die mit einem Berufsabschluss in einem neuen Berufsfeld abgeschlossen werden. Die hierbei erworbenen Fähigkeiten sind äquivalent zu den bei einer Berufsausbildung erworben Fähigkeiten. Dementsprechend kann die Trainingsdauer bis zu 3 Jahren betragen. Im Durchschnitt sind 21 Monate für den Abschluss der beruflichen Neuausrichtung vorgesehen. Lechner et. al (2011) evaluieren die langfristigen Auswirkungen einer beruflichen Neuausrichtung. Der Studie zugrunde liegen administrative Daten, die das Einkommen von Teilnehmer an verschieden Trainingsmaßnahmen in den Jahren 1992 bis 1994 über die nachfolgenden 8 Jahre umfassen. Der Datensatz ist auf Westdeutschland beschränkt. Die Autoren geben einen kumulierten Effekt der beruflichen Neuausrichtung auf das Einkommen von 37.281,90€ über 8 Jahre an. Nach Berechnung der effektiven Besteuerung ergeben sich unter Berücksichtigung der Diskontrate von 3% für den MVPF relevante Effekte auf (i) das Nettoeinkommen von plus `r format(res$retraining$net_income_increase)`€ und (ii) auf das Steueraufkommen von plus `r format(res$retraining$tax_revenue_increase, T)`€. Lechner et. al (2011) geben die Ausgaben für berufliche Neuausrichtungen mit 20.983€ pro Teilnehmer an. Die Nettokosten betragen somit 20.983€ - `r format(res$retraining$tax_revenue_increase, T)`€ = `r format(res$retraining$government_net_costs)`€. Der MVPF beträgt `r format(res$retraining$willingness_to_pay)`€ / `r format(res$retraining$government_net_costs)`€ = `r format(res$retraining$mvpf)`.

## Übungsfirma
Durch die Beschäftigung in einer Übungsfirma wurden Tätigkeiten in einem bestimmten Berufsfeld simuliert. Dabei sollen die Fähigkeiten, die an einem echten Arbeitsplatz benötigt werden, erlernt und ausgebaut werden. Normalerweise waren Teilnehmer für 6-12 Monate an einer Übungsfirma angestellt. Lechner et. al (2011) evaluieren die langfristigen Auswirkungen einer Beschäftigung an einer Übungsfirma. Der Studie zugrunde liegen administrative Daten, die das Einkommen von Teilnehmender an verschieden Trainingsmaßnahmen in den Jahren 1992 bis 1994 über die nachfolgenden 8 Jahre umfassen. Der Datensatz ist auf Westdeutschland beschränkt. Die Autoren geben einen kumulierten Effekt der Übungsfirma auf das Einkommen von 23.548€ über 8 Jahre an. Nach Berechnung der effektiven Besteuerung ergeben sich unter Berücksichtigung der Diskontrate von 3% für den MVPF relevante Effekte auf (i) das Nettoeinkommen von plus `r format(res$practiceFirm$net_income_increase)`€ und (ii) auf das Steueraufkommen von plus `r format(res$practiceFirm$tax_revenue_increase, T)`€. Lechner et. al (2011) geben die Ausgaben für die Finanzierung der Übungsfirma mit 20983€ pro Teilnehmer an. Die Nettokosten betragen somit 20983€ - `r format(res$practiceFirm$tax_revenue_increase, T)`€ = `r format(res$practiceFirm$government_net_costs)`€. Der MVPF ist daher aufgrund der positiven Zahlungsbereitschaft unendlich.