ba---
title: "Absenkungen des Spitzensteuersatzes"
output: html_document
---

```{r echo=FALSE, include=FALSE}
# Run the code necessary to get a list named res to access all the results. (Returned from listifyResults(.)) Probably it makes sense to load from disk, because caluclating every time is really slow.
res <- readRDS(file="results.RData")
format <- function(result) {
  toString(round(result,2))
}
```

## Reformen
 Die Einkommenssteuer ist eine der wichtigsten Säulen der Finanzierung des Staatshaushaltes. Im Jahr 2017 betrug das Steueraufkommen welches durch die Einkommenssteuer generiert wurde circa 300 Milliarden Euro [(Destatis, 2021)](https://www.destatis.de/DE/Themen/Staat/Steuern/Lohnsteuer-Einkommensteuer/Tabellen/gde.html). Ein zentraler Bestandteil eines jeden Einkommensteuersystems ist die Höhe des Spitzensteuersatzes. Das deutsche Finanzministerium dokumentiert die Tarifgeschichte der Einkommenssteuer ab dem Jahr 1958 [(BMF, 2021)](https://www.bmf-steuerrechner.de/ekst/eingabeformekst.xhtml). Insgesamt gab es mit Ausnahme der Einführung eines weiteren Tarifbrackets für sehr hohe Einkommen im Jahr 2007 nur zwei separate Reformen, die eine Anpassung des Spitzensteuersatzes vornahmen.  Im Jahr 1990 wurde der Spitzensteuersatz von 56% auf 53% abgesenkt. Die zweite relevante Reform des Spitzensteuersatzes sah eine schrittweise Absenkung des Spitzensteuersatzes von 53% auf 42% am Anfang der 2000er Jahre vor. Zwischen 1999 und 2001 wurde der Spitzensteuersatz von 53% auf 48,5% gesenkt. Mit Beginn des Jahres 2004 folgte eine Absenkung auf 45%. Zum 1. Januar 2005 wurde der Spitzensteuersatz auf sein heutiges Niveau von 42% gesenkt.

## Methodik
 Um das Kosten-Nutzen Verhältnis dieser Reformen, also den Marginal Value of Public Funds (MVPF) zu berechnen, muss der Nutzen der Steuersenkung für die Steuerzahler dem Steueraufkommensrückgang gegenüber gestellt werden. Zur Vereinfachung der Berechnung werden die Steuerersparnisse eines exemplarischen Spitzensteuersatzzahlers auf einen Euro normiert. Der Nutzen beträgt somit einen Euro. Die Nettokosten aus Sicht des Staates einer Steuersenkung in Höhe von einen Euro sind typischerweise kleiner als ein Euro, da eine Absenkung des Spitzensteuersatzes die marginalen Arbeitsanreize von Personen, die den Spitzensteuersatz zahlen verbessern. Die Stärke dieses Effekts ist eine empirische Frage zu der es umfangreiche internationale Literatur gibt. Der Parameter der in dieser Literatur bestimmt wird, ist die sogenannte Elasticity of Taxable Income (ETI). Diese gibt an wie stark das zu versteuernde Einkommen, auf eine Senkung des Steuersatzes reagiert. Für die Berechnung des MVPF wird ein Wert von 0.338 für die ETI angenommen. Dieser Wert stammt aus einer von [Doerrenberg (2015)](https://www.cesifo.org/DocDL/cesifo1_wp5369.pdf) aus deutschen Daten geschätzten Spezifikation und liegt in etwa im Mittel der Schätzungen aus der internationalen Literatur. Um den MVPF endgültig zu bestimmen sind Annahmen über die Einkommensverteilung der oberen Einkommen notwendig. Es wird eine Paretoverteilung angenommen. Diese wird mit Daten der [World Inequality Databse](https://wid.world) aus dem Jahr der Steuerreform parametrisiert.

## Ergebnisse

 Jahr | MVPF | Steuersatz vor Reform | Steuersatz nach Reform
 ------------- | ------------- | ------------- | -------------
 1990 |  `r format(res$taxReform1990$mvpf)` | 56% | 53%
 2001 |  `r format(res$taxReform2001$mvpf)` | 53% | 48.5%
 2004 |  `r format(res$taxReform2004$mvpf)` | 48.5% | 45%
 2005 |  `r format(res$taxReform2005$mvpf)` | 45% | 42%

 Die resultierenden MVPFs deuten auf erhebliche fiskalische Externalitäten bei den genannten Senkungen des Spitzensteuersatzes hin. Bei der Senkung des Spitzensteuersatzes von 53% auf 48,5% zwischen den Jahren 1999 und 2001 konnten 76% der Ausgaben für die Steuersenkung wieder durch gestiegene Bruttoeinkommen der Steuerzahler zurückgewonnen werden. Bei der finalen Anpassung des Spitzensteuersatzes, welche den niedrigsten MVPF aller Steuerreformen aufweist (`r format(res$taxReform2005$mvpf)`), konnten weiterhin 53% der Ausgaben zurückgewonnen werden. Es zeigt sich ein Trend, dass spätere Reformen die den Spitzensteuersatz immer weiter senkten, tendenziell niedrigere MVPFs als frühere Reformen aufweisen. Alle Absenkungen des Spitzensteuersatzes brachten im Durchschnitt mindestens 2 Euro pro netto eingesetztem Euro Steuergeld für Zahler des Spitzensteuersatzes. Die Steuersenkungen konnten somit effektiv Nettoeinkommen erhöhen. Dennoch muss bei der Interpretation dieser MVPFs berücksichtigt werden, dass die Begünstigten bereits vor der Reform hohe Einkommen aufwiesen.



