---
title: "Arbeitslosenversicherung"
output:
    html_document:
        fig_retina: 1
---

```{r echo=FALSE, include=FALSE}
# Run the code necessary to get a list named res to access all the results. (Returned from listifyResults(.)) Probably it makes sense to load from disk, because caluclating every time is really slow.
res <- readRDS(file="results.RData")
number_of_js_plots <- 0

format <- function(result, flipsign = FALSE) {
  if (flipsign) {
    result = - result
  }
  prettyNum(round(result,2), big.mark = ".", decimal.mark = ",")
}

library(ggplot2)
library(rjson)
library(scales)
library(showtext)

# Try to load the alternative font that is used in the pdf exports.
# If this font is not installed / cannot be found, the standard one will be used
tryCatch({
  plot_font <<- "Calibri"
  font_add(plot_font, "OpenSans-Regular.ttf")
}, error = function(e) {
  warning("Font is not installed. Plots are going to use the standard font instead.")
  plot_font <<- "sans"
})
showtext_auto()

makePlot <- function(program, type, heading = "", js = T) {
  if (missing(program) || missing(type)) {
    print("Need to specify program and type")
    return(0)
  }

  label <- switch(type, "wtp" = "Zahlungsbereitschaft", "cost" = "Fiskalische Kosten")
  variable <- switch(type, "wtp" = "willingness_to_pay", "cost" = "government_net_costs")

  if (js == TRUE) {
    if (number_of_js_plots > 0) {
      return(htmltools::HTML(sprintf(r"(<canvas id="chart%s" style="width: 100%%; height: %ipx"></canvas>
      <script>
      async function drawGraphs() {
        while(true) {
          if (content_loaded) {
            break;
          }
          else {
            await new Promise(r => setTimeout(r, 200));
          }
        }
        drawChart(unmodified_dataset, "%s", "%s", "%s");
      }
      drawGraphs();
      </script>
      )", paste0(program,variable), 170, variable, program, heading)))
    }

    # We have to split this in multiple strings because sprintf cannot print into strings longer than 8000 characters..
    variable_decs <- sprintf(r"(<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.0/chart.min.js"></script>
  <canvas id="chart%s" style="width: 100%%; height: %ipx"></canvas>
  <script>
    var unmodified_dataset;
    var document_root = "";
    var content_loaded = false;
    var additional_program_info;
    var categories;
    var colors;
    var variable_mapping;
    var tooltip_counter = 1;
    )", paste0(program,variable), 170)

    functions <- r"(async function loadJSON(url) {
    var json;
    await fetch(url).then(response => {
        json = response.json();
    });
    return json;
    }

    async function readjson(assumption_string) {
    // depends on additional_program_info being loaded as we need some way of determining which government policies exist before this function can be called

    // This will be the array carrying the data. It should be compatible to the array returned from readcsv with the only difference that the json format omits all the keys with NA values.
    var json_as_array;

    // First we need to get a list of all programs. Where the entries are strings
    var programs = additional_program_info.map(program => {
        return program.program_identifier;
    });

    // Individual json requests to all of the programs
    var requests = programs.map(program => {
        // Note: usually one would expect that this code runs the loadJSON and stores the
        // result in requests. This is not what we want, as the http requests should be
        // run in parallel for better performance. Fortunately, this is not what is happening. loadJSON is a async function. And async functions return promises. which are not automatically resolved.
        return loadJSON(document_root + "data/" + program + "/" + assumption_string + ".json");
    });

    // Resolve promises in parallel
    await Promise.all(requests).then((result) => json_as_array = result);

    // This loop merges the loaded ddata with the details about each reform (description, sources, age etc..) form programs.json. The resulting array of objects then contains all relevant data.

    for (var i = 0; i < json_as_array.length; i++) {
        Object.assign(json_as_array[i], additional_program_info[i]);
        // Rename program identifier to program. (For compatibility with the old solution)
        json_as_array[i]["program"] = json_as_array[i]["program_identifier"];
        delete json_as_array[i]["program_identifier"];
    }

    unmodified_dataset = JSON.parse(JSON.stringify(json_as_array));

    // sort by category & ensure that categories is defined already
    if (typeof(categories) != "undefined") {
        unmodified_dataset.sort(function(a, b){
            return categories.indexOf(a.category) - categories.indexOf(b.category);
        });
    }
    return json_as_array;
}

function getScalesMinMax(program) {
    // we want the same scale on all of the bar plots. To ensure this we calculate the required min length of the x-axis for each plot and apply the largest to all.
    let relevant_datapoint = unmodified_dataset.find(function (datapoint) {
        return (datapoint.program === program);
    });

    let max = addAllPositivesSubtractAllNegatives([
        Math.abs(parseFloat(relevant_datapoint["willingness_to_pay"]),
            -Math.abs(parseFloat(relevant_datapoint["government_net_costs"])))
    ]);
    let mappingEntry;

    for (let i = 0; i < variable_mapping.length; i++) {
        if (variable_mapping[i].program === program) {
            mappingEntry = variable_mapping[i];
            break;
        }
    }

    barComponents = mappingEntry["willingness_to_pay"];
    let array = [];
    let component;
    for (component in barComponents) {
        array.push(parseFloat(relevant_datapoint[component]));
    }
    max = Math.max(addAllPositivesSubtractAllNegatives(array), max);


    barComponents = mappingEntry["government_net_costs"];
    array = [];
    for (component in barComponents) {
        array.push(parseFloat(relevant_datapoint[component]));
    }
    max = Math.max(addAllPositivesSubtractAllNegatives(array), max);

    return (max);
}

function selectColor(number, background = false) {
    // returns a string in the format rgba(123,123,123,0.6)
    let background_opa = 0.7
    let foreground_opa = 0.9
    if (number > colors.length) {
        console.log("Color not in range of supplied colors in colors.json");
        // Reuse last color in this case
        number = colors.length;
    }
    color_triple = colors[number - 1];
    return `rgba(${color_triple[0]},${color_triple[1]},${color_triple[2]},${background ? background_opa : foreground_opa})`;
}

function addAllPositivesSubtractAllNegatives(array) {
    let negative = 0;
    let positive = 0;
    let i;
    for (i = 0; i < array.length; i++) {
        if (array[i] > 0) {
            positive += array[i];
        }
        else {
            negative -= array[i];
        }
    }
    return (Math.max(Math.abs(positive), Math.abs(negative)));
}

function generateBarData(csv_as_array, variable_to_plot, program) {
    let datasets = [];
    let barComponents;
    let bar_counter = 1;
    let relevant_datapoint = unmodified_dataset.find(function (datapoint) {
        return (datapoint.program === program);
    });
    if (variable_to_plot === "mvpf") {
        datasets.push({
            label: "Government Net Cost",
            data: [parseFloat(relevant_datapoint["government_net_costs"])],
            backgroundColor: selectColor(bar_counter, true),
            borderColor: selectColor(bar_counter),
        });
        datasets.push({
            label: "Willingness to Pay",
            data: [relevant_datapoint["willingness_to_pay"]],
            backgroundColor: selectColor(bar_counter + 1, true),
            borderColor: selectColor(bar_counter + 1),
        });
        bar_counter += 2;
        return (datasets);
    }
    for (let i = 0; i < variable_mapping.length; i++) {
        if (variable_mapping[i].program === program) {
            barComponents = variable_mapping[i][variable_to_plot];
            break;
        }
    }
    for (component in barComponents) {
        datasets.push({
            label: barComponents[component],
            data: [relevant_datapoint[component]],
            backgroundColor: selectColor(bar_counter, true),
            borderColor: selectColor(bar_counter)
        });
        bar_counter++;
    }
    bar_counter = 1;
    return (datasets);
}
)"
    drawChart <- r"(function drawChart(csv_as_array, variable_to_plot, program, heading = "") {
    let chartElement = document.getElementById('chart' + program + variable_to_plot);
    // Get Plotting range
    let range = getScalesMinMax(program);
    let chart = new Chart(chartElement, {
        type: 'bar',
        data: {
            labels: '.', // In ChartJS Beta 3.0 this could be left empty. If we leave it empty in 3.3, there is no graph drawn anymore. (And the tooltip is now shared for all areas of the chart in 3.3).
            datasets: generateBarData(csv_as_array, variable_to_plot, program)
        },
        options: {
            indexAxis: 'y',
            responsive: false,
            maintainAspectRatio: false,
            aspectRatio: 4,
            //devicePixelRatio: 4, //Set this to save a high res png. Otherwise leave default
            plugins: {
                title: {
                    display: true,
                    text: heading,
                    align: "start",
                    position: "top"
                },
                legend: {
                    position: 'bottom',
                    usePointStyle: true,
                    onClick: () => {} //This disables the ability to click on the legend and remove effects.
                },
                tooltip: {
                    enabled: true,
                    displayColors: false,
                    bodyColor: "black",
                    backgroundColor: "white",
                    borderWidth: 2,
                    cornerRadius: 8,
                    bodyFont: {weight: 600},
                    borderColor: "#2b6ebe",
                    mode: 'nearest',
                    callbacks: {
                        title: function (data) {
                            return null;
                        }
                    }
                }
            },
            scales: {
                x: {
                    stacked: true,
                    ticks: {
                        maxTicksLimit: 3
                    },
                    grid: {
                        drawOnChartArea: false,
                        lineWidth: 0,
                        tickWidth: 1
                    },
                    min: -range,
                    max: range,
                    afterTickToLabelConversion: function(data) {
                        // this adds € signs to the tick marks on the x-axis.
                        let ticks = data.ticks;
                        for (var i = 0; i < ticks.length; i++) {
                            ticks[i].label = ticks[i].label.replace(".", "placeholder").replace(",", ".").replace("placeholder", ",") + "€";
                        }
                        return data;
                    }
                },
                y: {
                    stacked: true,
                    display: false
                }
            }
        }
    });
})"
    js_exec <- sprintf(r"(if (true) {
        // load the dataset:
        Promise.all([
        loadJSON(document_root + "data/programs.json"),
        loadJSON(document_root + "data/categories.json")
    ]).then(return_values => {
        additional_program_info = return_values[0];
        categories = return_values[1];
        return Promise.all([
            readjson("default"),
            loadJSON(document_root + "data/variable_mapping.json"),
            loadJSON(document_root + "data/colors.json")
        ]);
    }).then((return_values) => {
        variable_mapping = return_values[1];
        colors = return_values[2];
        drawChart(return_values[0], "%s", "%s", "%s");
        content_loaded = true;
    });
}
</script>)",variable, program, heading)
    number_of_js_plots <<- number_of_js_plots + 1
    return(htmltools::HTML(paste0(variable_decs, functions, drawChart, js_exec)))
  }


  variable_mapping = rjson::fromJSON(file = "variable_mapping.json")

  # Construct the dataset
  for (i in 1:length(variable_mapping)) {
    if (variable_mapping[[i]]$program == program) {
      relevant_data <- variable_mapping[[i]]
    }
  }

  colors <- c(rgb(46,139,87, maxColorValue = 255),
              rgb(30,144,255, maxColorValue = 255),
              rgb(255,165,0, maxColorValue = 255),
              rgb(220,20,60, maxColorValue = 255),
              rgb(0,128,128, maxColorValue = 255),
              rgb(0,0,139, maxColorValue = 255),
              rgb(255,20,147, maxColorValue = 255),
              rgb(165,42,42, maxColorValue = 255),
              rgb(154,205,50, maxColorValue = 255),
              rgb(196, 196, 126, maxColorValue = 255),
              rgb(189,189,189, maxColorValue = 255))

  getValue <- function(name) {
    return(res[[program]][[name]])
  }
  getRange <- function(data) {
    positives = 0
    negatives = 0
    for (i in 1:length(data$values)) {
      if (data$values[[i]] >= 0) {
        positives = positives + data$values[[i]]
      }
      else {
        negatives = negatives - data$values[[i]]
      }
    }
    return(max(c(positives, negatives)))
  }

  data <- data.frame(values = sapply(names(relevant_data[[variable]]), getValue),
                     labels = unlist(relevant_data[[variable]], use.names=FALSE), x = 0)

  plot <- ggplot(data) + geom_col(aes(y = values, x = x, fill = labels)) +
    coord_flip() + theme(legend.position = "bottom") +
    scale_y_continuous(labels = function(x) paste0(x, "€"), limits = c(-getRange(data), getRange(data))) +
    scale_fill_manual(values = colors) +
    scale_shape_manual(values = 21) +
    ylab(label) +
    guides(fill=guide_legend(ncol=3,byrow=TRUE)) +
    theme_minimal(base_size=20,  base_family=plot_font) %+replace%
      theme (
      # axis.line.x|y control whether the x and y axis are drawn. It can look stylish to omit one or both:
      # axis.line.y = element_blank() to omit
      # e.g: axis.line.x = element_line(color = "darkgrey", size = 0.5) to draw
      axis.line.y = element_blank(),
      axis.line.x = element_line(color = "darkgrey", size = 0.75),
      axis.title.y=element_blank(),
      panel.border = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_blank(),
      # Enable or Disable Axis ticks:
      axis.ticks = element_line(color = "darkgrey", size = 0.75),
      axis.ticks.y = element_blank(),
      # Removes Legend Explanation:
      legend.title=element_blank(),
      # Set location of legend:
      legend.position = "bottom",
      # Legend font size
      legend.text = element_text(size=10.5),
      # Axis (ticks) size
      axis.text = element_text(size=11.5),
      axis.text.y = element_blank(),
      # Axis label size
      axis.title = element_text(size=14),
      # Change Legend Stacking to vertical:
      legend.box="vertical"
      )
  print(plot)
}

```

## Institutionelle Rahmenbedingungen
Die Arbeitslosenversicherung bieten einen Schutz gegen die negativen finanziellen Auswirkungen von Arbeitslosigkeit. Im Fall eines unerwarteten Jobsverlusts helfen die Arbeitslosengeldzahlungen Einkommensverluste abzufedern. Die Arbeitslosenversicherung hilft also die Unsicherheit in Bezug auf das persönliche Einkommen zu reduzieren. Durch diese Versicherungswirkung entsteht durch das Arbeitslosengeld ein Wert, der den nominalen Wert des gezahlten Arbeitslosengeldes übersteigt. Auf der anderen Seite reduziert der Erhalt von Arbeitslosengeld die Notwendigkeit eine neue Beschäftigung aufzunehmen. Es entstehen so fiskalische Kosten durch einen länger anhaltenden Bezug von Arbeitslosengeld und durch entgangene Einkommenssteuerzahlungen. Aus diesem Grund ist die maximale Bezugsdauer des Arbeitslosengeldes I begrenzt. Im deutschen Arbeitslosenversicherungssystem hängt die maximale Bezugsdauer von Arbeitslosengeld I von dem Alter des Versicherten ab. Das System ist so ausgestaltet, dass es Altersgrenzen gibt, an denen die maximale Bezugsdauer sprunghaft ansteigt. Diese Sprungstellen können ausgenutzt werden, um den Zusammenhang zwischen der Bezugsdauer des Arbeitslosengeldes und der Dauer der Arbeitslosigkeit zu bestimmen.

## Methodik
 Um den MVPF zu berechnen, muss der Nutzen der Risikoreduktion den fiskalischen Kosten der Bereitstellung gegenübergestellt werden. Zur Vereinfachung der Berechnung wird eine Ausweitung der Arbeitslosenversicherung um einen Euro betrachtet. Die Berechnung des MVPF folgt der von Hendren & Sprung-Keyser (2020) verwendeten Methodik zur Berechnung des MVPFs von Arbeitslosenunterstützung. Der MVPF einer Arbeitslosengeldausweitung kann dargestellt werden als: $$\textrm{MVPF} = \frac{1 + \textrm{Wert Risikoreduktion}}{1 + \textrm{FE}}$$. Der Zähler besteht aus der Arbeitslosengeldzahlung in Höhe von einem Euro plus der Wertschätzung für die Risikoreduktion. Der Wert der Risikoreduktion kann als das Produkt der relativen Risikoaversion und dem Konsumrückgang bei Arbeitslosigkeit ausgedrückt werden. Schmieder & von Wachter (2016) liefern einen Überblick über Studien, die den Konsumrückgang bei Arbeitslosigkeit untersuchen. Die Schätzungen liegen im Bereich von fünf bis 25 Prozent. Es gibt keine auf Deutschland bezogenen Studie. Es wird ein Konsumrückgang am unteren Ende der Schätzungen in Höhe von acht Prozent angenommen. Der Koeffizient der relative Risikoaversion wird auf zwei festgelegt. Diese Annahmen entsprechen den Annahmen von Hendren & Sprung-Keyser (2020). Die Zahlungsbereitschaft für die Ausweitung der Arbeitslosenversicherung beträgt damit immer 1 + 0,08 ✕ 2 = 1,16. Der Nenner der oben dargestellten MVPF-Formel besteht aus der auf einen Euro normierten Zahlung des Arbeitslosengeldes plus der fiskalischen Externalität. Die fiskalische Externalität umfasst die Mehrkosten die aufgrund der reduzierten Beschäftigungsanreize bei einer Arbeitslosengeldausweitung entstehen. Die Berechnung der fiskalische Externalität ist komplex und umfasst einige Parameter, darunter die Lohnersatzrate, der Steuersatz, die maximale Bezugsdauer und der Effekt einer Verlängerung der Bezugsdauer auf die Dauer der Arbeitslosigkeit. Die genaue Formel und deren Herleitung kann in Schmieder & von Wachter (2016) S.560-562 nachgeschlagen werden.

## Ergebnisse
  Der wichtigste Parameter in der Berechnung des MVPFs ist der Effekt der Bezugsdauer auf die Dauer der Arbeitslosigkeit. Sollte es keinen negativen Anreizeffekt bei der Ausweitung von Bezugszeiten geben, wäre die fiskalische Externalität gleich null und der MVPF der Arbeitslosenversicherung gleich 1,16. Ein höherer MVPF wäre nur möglich, wenn die Zahlung von Arbeitslosengeld die Jobsuche beschleunigen würde. Die Auswirkung der Länge des Arbeitslosengeldbezugszeitraums auf die Dauer der Arbeitslosigkeit ist Gegenstand wirtschaftswissenschaftlicher Forschung. Schmieder et al. (2012) nutzen die bereits erwähnten Sprungstellen in der deutschen Arbeitslosenversicherung, an denen sich die Anspruchsdauer ändert, um ein Regression Discontinuity Design zu implementieren. Unter Verwendung eines großen administrativen Datensatzes, der die Jahre 1987 bis 1999 abdeckt, zeigen die Autoren, dass die Verlängerung der Anspruchsdauer von 42-Jährigen um einen Monat die Dauer der Arbeitslosigkeit um 0,13 Monate verlängert. Daraus ergibt sich eine fiskalische Externalität von 0,29. Der MVPF beträgt 1,16 / 1,29 = 0,90. Bei der Verwendung anderer Sprungstellen im Alter von 44 und 49 bleiben die Resultate praktisch unverändert. Eine ähnliche Studie von Caliendo et al. (2013), bei der eine Sprungstelle im Alter von 45 Jahren verwendet wird, legt einen etwas niedrigeren MVPF von 0,62 nahe.

Im Jahr 2006 wurde die Bezugsdauer des Arbeitslosengeldes im Rahmen der Hartz-Reformen gekürzt. Petrunyk & Pfeifer (2018) evaluieren die Auswirkung der Reform auf Personen mit gesundheitlichen Beeinträchtigungen. Im Gegensatz zu den anderen beiden Studien basiert die Identifikation nicht auf Diskontinuitäten im Leistungssystem, sondern auf der Tatsache, dass nicht alle Altersgruppen von der Hartz-Reform betroffen waren. Lediglich für Personen, die zum Zeitpunkt des Verlusts der Arbeitsstelle älter als 45 waren, wurde die Bezugsdauer gekürzt. Die Resultate von Petrunyk & Pfeifer (2018) suggerieren einen kleineren Anreizeffekt von im Durchschnitt 0.048 Monate kürzerer Arbeitslosigkeit bei Kürzung des Bezugszeitraums um einen Monat. Es resultiert ein MVPF von 1.08.

Die folgende Tabelle liefert eine Übersicht über alle MVPF Schätzungen:

 Jahr |  MVPF  | FE | Alter | Studie
 ---- | ----| ---- | ---- | ----
 1993 |  `r format(res$unemploymentBenefits42$mvpf)`| `r format(res$unemploymentBenefits42$fiscal_externality)` | 42 | Schmieder et al. (2012)
 1993 |  `r format(res$unemploymentBenefits44$mvpf)` | `r format(res$unemploymentBenefits44$fiscal_externality)` | 44 | Schmieder et al. (2012)
 1993 |  `r format(res$unemploymentBenefits49$mvpf)`  | `r format(res$unemploymentBenefits49$fiscal_externality)` | 49 | Schmieder et al. (2012)
 2002 |  `r format(res$unemploymentBenefits2002$mvpf)`| `r format(res$unemploymentBenefits2002$fiscal_externality)` | 45 | Caliendo et al. (2013)
 2006 |  `r format(res$unemploymentBenefits2006$mvpf)`| `r format(res$unemploymentBenefits2006$fiscal_externality, T)` | >45 | Petrunyk & Pfeifer (2018)

